trigger:
  branches:
    include:
    - main
  paths:
    exclude:
      - README.md

pool:
  name: Default
  demands:
  - Agent.Name -equals masterhora2

variables: 
  dockerRegistry: 'localhost:5000'

steps:
- task: Gradle@4
  displayName: 'Gradle Clean'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'clean'

- task: Gradle@4
  displayName: 'Gradle Build'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'

- task: Gradle@4
  displayName: 'Gradle Dockerize'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'dockerize'
    options: '-Ppersistence=true'

- script: |
    docker tag sts:latest $(dockerRegistry)/sts:latest
    docker push $(dockerRegistry)/sts:latest
  displayName: 'Push sts docker image to docker registry'

- script: |
    docker tag identity-hub:latest $(dockerRegistry)/identity-hub:latest
    docker push $(dockerRegistry)/identity-hub:latest
  displayName: 'Push identity hub docker image to docker registry'

- script: |
    docker tag catalog-server:latest $(dockerRegistry)/catalog-server:latest
    docker push $(dockerRegistry)/catalog-server:latest
  displayName: 'Push catalog server docker image to docker registry'

- script: |
    docker tag controlplane:latest $(dockerRegistry)/controlplane:latest
    docker push $(dockerRegistry)/controlplane:latest
  displayName: 'Push controlplane docker image to docker registry'

- script: |
    docker tag dataplane:latest $(dockerRegistry)/dataplane:latest
    docker push $(dockerRegistry)/dataplane:latest
  displayName: 'Push dataplane docker image to docker registry'

- script: |
    cp -r deployment /opt/mvd
    cp docker-compose.yml /opt/mvd
  displayName: 'Copy deployment files to /opt/mvd'

- script: |
    cd /opt/mvd
    docker compose down
    docker compose pull
    docker compose up -d
  displayName: 'Run docker-compose to deploy provider'

- script: |
    docker system prune -a -f
  displayName: 'Cleanup local docker'
  condition: always()