trigger:
- main

pool:
  name: Default
  demands:
  - Agent.Name -equals masterhora2

steps:
- task: Gradle@4
  displayName: 'Gradle Build'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'