services:
  vault:
    image: hashicorp/vault:latest
    container_name: provider-vault
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://localhost:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: ["/bin/sh", "-c"]
    command:
      - vault server -dev
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 120s
    networks:
      - mvd

networks:
  mvd:
    name: mvd
    external: true